help_plus = """
HERE ARE THE BAN CODES FOR [×× CRYTONIX ××](https://t.me/CrytoniXinfo)
• `CTx01` - SPAM ADDING MEMBER
• `CTx02` - CHILD ABUSE
• `CTx03` - ILLEGAL
• `CTx04` - FRAUD PROMOTION  [ANY KIND]
• `CTx05` - PHISHING
• `CTx06` - BAN EVASION
• `CTx07` - RAID/SPAM INFLAMED
• `CTx08` - ADDING SPAMBOTS
• `CTx09` - KRIMINALANT
• `CTx10` - SCAMMER
• `CTx11` - ABUSE SPAM
• `CTx12` - IMPERSONATION
• `CTx13` - MD/BTC SCAM
• `CTx14` - RAID INITIALIZER
• `CTx15` - RAID PARTICIPANT
• `CTx16` - SPAMBOT
• `CTx17` - CYBER THREATENING / CYBER BULLY
• `CTx18` - NSFW SPAMMER
"""


__plugin_name__ = "Bancodes"
